version: '2.2'
 
services:
  rest_api:
    build: .
    container_name: rest_api
    restart: always
    environment:
      BUILD: "FALSE"
    ports:
      - "5000:5000"
    expose:
      - "5000"
    volumes:
      - ./rest_api:/rest_api
    depends_on:
      - elasticsearch
    command: ["/cmd.sh"]

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"



volumes:
  esdata1:
    driver: local

  