version: '2'
 
services:
  rest_api:
    build: .
    container_name: rest_api
    restart: always
    environment:
      MAPPING: "True"
      DELETE: "False"
      DATA: "True"
    ports:
      - "5000:5000"
    expose:
      - "5000"
      - "8000"
    volumes:
      - ./rest_api:/rest_api
    depends_on:
      - elasticsearch
    command: ["/cmd.sh"]
    networks:
      network:
        aliases:
          - web.network_elastic_backend

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g -Des.enforce.bootstrap.checks=true"
      - bootstrap.memory_lock=false
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      network:
        aliases:
          - elasticsearch.network_elastic_backend

volumes:
  esdata1:
    driver: local

networks:
  network:
    external:
      name: network_elastic_backend
