
version: '2.1'
services:
  db:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    networks:
      network:
        aliases:
          - db.network_elastic_backend
    volumes:
      - ./db-backups:/backups
    
  web:
    build: .
    container_name: django_web
    environment:
      ENV: DEV
    command: ["/wait-postgres.sh","db:5432","-t", "60","--","/cmd.sh"] 
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - db
    expose:
      - "5000"
    networks:
      network:
        aliases:
          - web.network_elastic_backend

networks:
  network:
    external:
      name: network_elastic_backend
