version: '2.1'
services:
  nginx:
    restart: always
    image: nginx
    container_name: nginx
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app
      - ./config/nginx:/etc/nginx/conf.d
    links:
      - web
    
  db:
    image: postgres
    ports:
      - "5432:5432"

  web:
    build: .
    environment:
      ENV: ENV
    command: ["/wait-postgres.sh","db:5432","-t", "60","--","/cmd.sh"] 
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - db