version: '2'
services:
  nginx:
    restart: always
    image: nginx
    container_name: nginx
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app
      - ./config/nginx:/etc/nginx/conf.d
    links:
      - web
    expose:
      - 5000
    networks:
      network:
        aliases:
          - nginx.network_elastic_backend
    
  db:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    networks:
      network:
        aliases:
          - db.network_elastic_backend
    volumes:
      - ./db-backups:/backups

  web:
    build: .
    container_name: django_web
    environment:
      ENV: ENV
    command: ["/wait-postgres.sh","db:5432","-t", "60","--","/cmd.sh"] 
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - db
    expose:
      - 5000
    networks:
      network:
        aliases:
          - web.network_elastic_backend

networks:
  network:
    external:
      name: network_elastic_backend
