#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

C:/Users/nosov/AppData/Local/Programs/Python/Python36-32/python.exe  C:/Users/nosov/PycharmProjects/format_test/.git/hooks/pre-commit.py --check