# Generated by Django 2.0.7 on 2018-07-24 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wikisearch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='page_rank',
            field=models.IntegerField(default=0, help_text='rank of the page', max_length=10000, verbose_name='page_ranl'),
        ),
    ]
