# Generated by Django 2.0.7 on 2018-07-30 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wikisearch', '0002_article_page_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='page_rank',
            field=models.IntegerField(
                default=0,
                help_text='rank of the page',
                verbose_name='page_rank'),
        ),
    ]
