# Generated by Django 2.0.7 on 2018-08-06 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wikisearch', '0004_auto_20180730_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='urls',
            field=models.CharField(default='None', help_text='url of wiki article', max_length=2000, verbose_name='URL'),
        ),
    ]
