# Generated by Django 2.0.7 on 2018-08-08 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wikisearch', '0006_auto_20180806_0438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='urls',
        ),
        migrations.AddField(
            model_name='article',
            name='links',
            field=models.TextField(default='None', help_text='url of wiki article', verbose_name='dependings links'),
        ),
    ]
