# Generated by Django 2.0.7 on 2018-08-09 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wikisearch', '0007_auto_20180808_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.CharField(help_text='url of wiki article', max_length=1000, verbose_name='URL'),
        ),
    ]
