# Generated by Django 2.1 on 2018-08-16 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wikisearch', '0009_auto_20180816_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='links',
            field=models.TextField(default='None', help_text='url of wiki article', verbose_name='dependings links'),
        ),
        migrations.AlterField(
            model_name='article',
            name='page_rank',
            field=models.FloatField(default=0, help_text='rank of the page', verbose_name='page_rank'),
        ),
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.CharField(help_text='url of wiki article', max_length=1000, verbose_name='URL'),
        ),
    ]
